### ISSUE TITLE
Umbraco V9

### ISSUE THREAD

**Issue by slag-manuel** [vendrcontrib/vendr-payment-provider-adyen#1]
Do you have any plans to mirgrate this for the new version of Umbraco V9?

**Comment by bjarnef** [comment]
Sure, I am working on a v2 release for Vendr 2.0 / Umbraco 8.17+ and Umbraco 9.0+
https://github.com/vendrcontrib/vendr-payment-provider-adyen/tree/v2/dev

Still need to test it further in v8 and v9. I'll check with @mattbrailsford if we can ship a pre-release and it will be very helpful if you want to help testing the payment provider 🤓😎🙌

**Comment by slag-manuel** [comment]
Perfect – yes of course 😊. I have a project next year, where I can test your implementation. Do you have a lot of experience with adyen ?

 

 

 

Von: Bjarne Fyrstenborg ***@***.***> 
Gesendet: Montag, 20. Dezember 2021 17:41
An: vendrcontrib/vendr-payment-provider-adyen ***@***.***>
Cc: Baumann Manuel ***@***.***>; Author ***@***.***>
Betreff: Re: [vendrcontrib/vendr-payment-provider-adyen] Umbraco V9 (Issue #1)

 

Sure, I am working on a v2 release for Vendr 2.0 / Umbraco 8.17+ and Umbraco 9.0+
https://github.com/vendrcontrib/vendr-payment-provider-adyen/tree/v2/dev <https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvendrcontrib%2Fvendr-payment-provider-adyen%2Ftree%2Fv2%2Fdev&data=04%7C01%7C%7C12cb4970206d45c0607608d9c3d7761f%7Cbeb7b05c08234a4cbfac3497745999f7%7C1%7C0%7C637756152430253400%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YHYPm%2BAYFMZn2QPr5Vwk4JXOSAApsJKHYm4PR2l9Cow%3D&reserved=0> 

Still need to test it further in v8 and v9. I'll check with @mattbrailsford <https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmattbrailsford&data=04%7C01%7C%7C12cb4970206d45c0607608d9c3d7761f%7Cbeb7b05c08234a4cbfac3497745999f7%7C1%7C0%7C637756152430253400%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Uj%2FNAokYtTnxzZqzkHN8gdCfTca0Za6G91eVNHtXUM4%3D&reserved=0>  if we can ship a pre-release and it will be very helpful if you want to help testing the payment provider 🤓😎🙌

—
Reply to this email directly, view it on GitHub <https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvendrcontrib%2Fvendr-payment-provider-adyen%2Fissues%2F1%23issuecomment-998092043&data=04%7C01%7C%7C12cb4970206d45c0607608d9c3d7761f%7Cbeb7b05c08234a4cbfac3497745999f7%7C1%7C0%7C637756152430253400%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nCYZUg0xZlHfGl2a3Z84RImfwA1SieMcy1SJbexm6A4%3D&reserved=0> , or unsubscribe <https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAM3QEJDCTDFRT2GUUCCXGE3UR5MARANCNFSM5KOC25NA&data=04%7C01%7C%7C12cb4970206d45c0607608d9c3d7761f%7Cbeb7b05c08234a4cbfac3497745999f7%7C1%7C0%7C637756152430253400%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=97BnsV5bMQsnXKyswueEfVUeF9bLoQBH5WoFjeSLrYU%3D&reserved=0> .
Triage notifications on the go with GitHub Mobile for iOS <https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C12cb4970206d45c0607608d9c3d7761f%7Cbeb7b05c08234a4cbfac3497745999f7%7C1%7C0%7C637756152430253400%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SNwdTnIu89g2QoJn4TpUHd50XWXgrWKy3rv6khSk1ko%3D&reserved=0>  or Android.

**Comment by bjarnef** [comment]
@slag-manuel not a lot, but I have tested the basically functionality and common features needed on a webshop like the payment request, cancel, charge and refund.

In v2 I still need to test it still works on Umbraco v8 and v9 - it should, but better safe than sorry.

**Comment by mattbrailsford** [comment]
There is a now a 2.0.0-rc0000 build of the Adyen provider on the unstable nuget feed at https://nuget.outfield.digital/unstable/vendr-contrib/v3/index.json

**Comment by bjarnef** [comment]
I'll close this as the v2.0.0 release is available here: https://www.nuget.org/packages/Vendr.Contrib.PaymentProviders.Adyen/
